ln -s ackrc ~/.ackrc 
ln -s applescript ~/.applescript 
ln -s bash ~/.bash 
ln -s bash_profile ~/.bash_profile 
ln -s bashrc ~/.bashrc
ln -s gemrc ~/.gemrc 
ln -s gitignore ~/.gitignore 
ln -s railsrc ~/.railsrc 
ln -s scripts ~/.scripts 
ln -s tmux.conf ~/.tmux.conf 
ln -s tmux.md ~/.tmux.md
