#!/bin/sh
#
# An example hook script to verify what is about to be committed.
# Called by "git commit" with no arguments.  The hook should
# exit with non-zero status after issuing an appropriate message if
# it wants to stop the commit.
#
# To enable this hook, rename this file to "pre-commit".

if git rev-parse --verify HEAD >/dev/null 2>&1
then
	against=HEAD
else
	# Initial commit: diff against an empty tree object
	against=4b825dc642cb6eb9a060e54bf8d69288fbee4904
fi

for FILE in `git diff-index --name-status $against -- | cut -c3-` ; do
    # Check if the file contains 'focus'
    if [ "grep ':focus' $FILE" ]
    then
	echo "================================================================================$(tput setaf 1)"
        echo "Unable to commit! You left the :focus on in $(tput bold)$FILE$(tput sgr0)$(tput setaf 7)"
	echo "================================================================================"
        exit 1
    fi
done
exit
